services:
  webui:
    build:
      context: .
    image: gemma-namecraft-ui
    ports:
      - "8157:80"
    restart: always
    command:
      sh -c "flutter run --release -d web-server --web-renderer=auto --web-port 80 --web-hostname 0.0.0.0"